version: '3.8'
services:
  app:
    container_name: theme_baker_app 
    restart: always
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    depends_on:
      - wordpress    
  mysql:
    image: mysql:latest
    container_name: theme_baker_mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: baker
      MYSQL_DATABASE: baker
      MYSQL_USER: baker
      MYSQL_PASSWORD: baker
  wordpress:
    image: wordpress:6.3.1
    container_name: theme_baker_wordpress
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./cms/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./cms:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: theme_baker_mysql
      WORDPRESS_DB_NAME: baker
      WORDPRESS_DB_USER: baker
      WORDPRESS_DB_PASSWORD: baker
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);     
        define( 'WP_ENVIRONMENT_TYPE', 'local');
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: theme_baker_phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: theme_baker_mysql
      MYSQL_ROOT_PASSWORD: baker
      UPLOAD_LIMIT: 30M      
volumes:
  mysql: